### ISSUE TITLE
Include official documentation

### ISSUE THREAD

**Issue by nilp0inter** [nilp0inter/autofirma-nix#23]
`AutoFirma`'s official documentation is hosted [here](https://github.com/ctt-gob-es/clienteafirma-docs)

Make a separate derivation that includes the relevant documentation (in the original format) and optionally an automatic transcription to a more portable format like Markdown or HTML.

**Comment by nilp0inter** [comment]
AutoFirma already provides user documentation from the UI by pressing F1.

The file _What's New_ could be included, but it appears to be out-of-sync.

**Comment by panchoh** [comment]
> The file What's New could be included, but it appears to be out-of-sync.

Easily fixed by renaming it to _What’s Old_ ;-P
