### ISSUE TITLE
Standalone package

### ISSUE THREAD

**Issue by 0david0mp** [nilp0inter/autofirma-nix#33]
Gracias por hacer el port, me has salvado **muchos** dolores de cabeza con autofirma, y es muy simple de usar.

Has pensado en hacer un paquete para hacer el port disponible desde `nixpkgs`, o desde `nur`?

**Comment by nilp0inter** [comment]
¡Me alegro de que te sea de utilidad! Contestando a tu pregunta, sí, es parte de nuestro roadmap (véase #20 para más información).  

Cierro este issue tentativamente, pero siéntete libre de añadir/preguntar lo que sea.

**Comment by 0david0mp** [comment]
muchas gracias por la respuesta!
